# Generated by Django 2.1 on 2018-10-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0002_auto_20180917_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDictSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('dictset', models.ManyToManyField(to='loginapp.PersonalDict')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DictSet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
