# Generated by Django 2.1 on 2018-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customdict', '0002_auto_20181028_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdictfile',
            name='file',
            field=models.FileField(upload_to='UserDictDir/'),
        ),
    ]
