# Generated by Django 2.1 on 2018-11-17 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='UserArticleDir/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticleFile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
