# Generated by Django 2.1 on 2018-11-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadArticle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticlefile',
            name='cache',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userarticlefile',
            name='hascache',
            field=models.BooleanField(default=False),
        ),
    ]
