# Generated by Django 2.1 on 2018-12-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadArticle', '0002_auto_20181117_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticlefile',
            name='NerField',
            field=models.TextField(default=''),
        ),
    ]
