# Generated by Django 2.1 on 2019-03-01 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadArticle', '0003_userarticlefile_nerfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='UserImgDir/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImgFile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
