# Generated by Django 2.1.7 on 2019-05-18 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('url', models.TextField(default='')),
                ('company', models.CharField(max_length=10)),
                ('positiveprob', models.FloatField()),
            ],
        ),
    ]
